_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 36
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 36
                - 53
                - 55
                - 77
            "3":
                - 2
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.0
            "8":
                - 3
                - 5
            "12": 0.18.0
            "13": windows-amd64
TopK:
    value: 20
batch_size:
    value: 4096
community_dropout_strength:
    value: 0.5
dataset:
    value: ml-100k
do_power_nodes_from_community:
    value: true
epochs:
    value: 2
items_dec_perc_drop:
    value: 0
items_top_percent:
    value: 0
model:
    value: LightGCN
users_dec_perc_drop:
    value: 0.7
users_top_percent:
    value: 0.1
